### ISSUE TITLE
vial requires uncraftable potion

### ISSUE THREAD

**Issue by KenyMylankca** [Mnesikos/LilCritters#15]

**Comment by JoelZBub** [comment]
Which vial?
Which Potion?
Which version of the mod?

I'm saving the link to this report as an example of how *not* to do an issue report.

**Comment by KenyMylankca** [comment]
LOL do you have a brain? your mod has only 1 vial, and theres only 1 uncraftable potion in minecraft which is a pink bottle thing. version doesn't matter, you just could check your vial. what the fuck ever, zawa dev already said he wont fix it and i wont be using it so it doesnt matter you fix it or not. i reported a bug for you to have a chance to make your mod better but you behaving like a selfish asshole, i did a mistake of doing this. so fuck off

**Comment by CammiePone** [comment]
Keny, the reason this is a bad bug report is because:

1. You didn't specify the mod version
2. You didn't mention any mods you may have installed that could cause this

I can understand why you wouldn't explain what vial, if there's only one, but at the same time just saying "requires uncraftable potion" could be interpreted as a potion that just can't be crafted, not as THE Uncraftable Potion.

What you did here was you provided a not-so-helpful bug report, then got mad when asked for more info and the mention that the bug report was an example of how to not report bugs. This isn't the worst one I've seen, but it's definitely not one of the best either.
